### PR TITLE
ADD_PATH and other features

### PR DESCRIPTION
**Pull request by pforemski**
The original ADD_PATH implementation contributed by @netixx.

### CODE REVIEW

**Comment by netixx** [comment]
I am having issue running this branch with the speaker not starting (not sending OPEN message).

I am using the following bit of code
```
spk := speaker.NewSpeaker(ctx)
	spk.Options.LocalCaps = cs
	spk.Options.Passive = false
	spk.Options.LocalASN = 16276
	spk.Options.LocalHoldTime = 15
	spk.Options.LocalId = netip.MustParseAddr("XX")
	spk.Options.RemoteASN = 16276
	spk.Attach(p, msg.DIR_L)
```

after a little bit of debug, it looks like the start event is not propagated
```
for _, h := range hs {
			fmt.Printf("evt b %+v\n", ev)
			// skip handler?
			if h == nil || h.Dropped {
				continue // dropped
			} else if h.Dir&ev.Dir == 0 {
				continue // different direction
			} else if h.Enabled != nil && !h.Enabled.Load() {
				continue // disabled
			}
			fmt.Printf("evt %+v\n", ev)
```
in `pipe/event.go`

In my logs I see `evt b E1:bgpfix/pipe.START` but no "evt E1:bgpfix/pipe.START`.

I found that this condition matches the start event:
`h.Dir&ev.Dir == 0`
because both Dir are 0 in that case.

I think we need either  `h.Dir != 0 && h.Dir&ev.Dir == 0` in this condition
or
set the Dir on the OnStart handler pushed bu the speaker here: `po.OnStart(s.onStart)`

In the handler struct, there is
```
	Dir   msg.Dir     // if non-zero, limits the direction
```

Which would suggest that the first approach is the right one ?

**Comment by netixx** [comment]
It also doesn't seem to be reading the open messages from the remote for some reason ?

**Comment by pforemski** [comment]
Thanks so much for the review and for catching the bug. I've fixed it, improved a few more things, and tested on MRT files - LGTM.

@netixx would you have time to re-evaluate now?

p.s. apologies for late response ;)

**Comment by pforemski** [comment]
Hey @netixx a friendly nudge here :) Please let me know if you're planning to re-evaluate, otherwise I'll just merge the branch and release.

**Pull request merged**
